apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.sa_password | b64enc | quote}}